repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        pass_filenames: false
      - id: cargo-clippy-fix
        name: cargo clippy fix
        entry: cargo clippy --fix --allow-dirty --allow-staged --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
